apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-deployment
  labels:
    app: member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
        - name: ac2-2024-member-container
          imagePullPolicy: Never
          image: ac2-2024-member-container:latest
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: member-service
spec:
  selector:
    app: member
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
