name: AWS CD Back
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - featurecd
jobs:
  DeployToAWSBack:
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRoleAC2
          role-session-name: github-action

      - name: Setting stage and stack name
        run: |
          echo "STAGE=${{ github.ref_name }}" 
          PROJECT_NAME=$(echo ${{ github.event.repository.name }} | sed -e 's/[-_]/ /g' | awk '{for(i=1;i<=NF;i++)sub(/./,toupper(substr($i,1,1)),$i)}1' | sed -e 's/ //g')
          echo "PROJECT_NAME=${PROJECT_NAME}"
          echo "STACK_NAME=${PROJECT_NAME}StackBack${{github.ref_name}}"

          echo "STACK_NAME=${PROJECT_NAME}StackBack${{github.ref_name}}" >> $GITHUB_ENV
          echo "PROJECT_NAME=${PROJECT_NAME}" >> $GITHUB_ENV

      - name: Installing Dependencies to Deploy
        run: |
          cd iac
          npm install -g aws-cdk
          npm i
      - name: Installing Dependencies
        run: |
          cd back
          pnpm i
          pnpm run build
      - name: Setup envs
        run: |
          echo AWS_REGION=${{ vars.AWS_REGION }} >> $GITHUB_ENV
          echo AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} >> $GITHUB_ENV
          echo GITHUB_REF_NAME=${{ github.ref_name }} >> $GITHUB_ENV

          echo ${{ env.AWS_REGION }}
          echo ${{ env.AWS_ACCOUNT_ID }}
          echo ${{ env.STACK_NAME }}
          echo ${{ env.GITHUB_REF_NAME }}

      - name: Deploy with CDK
        run: |
          cd iac
          cdk synth
          cdk deploy --require-approval never
